# 确保已安装：pip install pyecharts
import json
from pyecharts.charts import Map
from pyecharts import options as opts
from pyecharts.commons.utils import JsCode

# 国家信息字典：英文名 -> [音标, 中文名, 所属大洲, 领土面积, 人口]
# 覆盖全部 193 个联合国会员国，另含梵蒂冈、巴勒斯坦 2 个联大永久观察员国。
# 面积为常用公开口径（约数），人口为 2023—2024 年量级估算。
country_info = {
    # ---------------- 亚洲（47 会员国） ----------------
    "Afghanistan":  ["/æfˈɡænɪstæn/", "阿富汗", "亚洲", "约65.2万 km²", "约4250万"],
    "Armenia":      ["/ɑːrˈmiːniə/", "亚美尼亚", "亚洲（外高加索，有时归欧洲）", "约2.97万 km²", "约300万"],
    "Azerbaijan":   ["/ˌæzərˈbaɪdʒɑːn/", "阿塞拜疆", "亚洲（外高加索，有时归欧洲）", "约8.66万 km²", "约1010万"],
    "Bahrain":      ["/bɑːˈreɪn/", "巴林", "亚洲", "约787 km²", "约160万"],
    "Bangladesh":   ["/ˌbæŋɡləˈdɛʃ/", "孟加拉国", "亚洲", "约14.8万 km²", "约1.73亿"],
    "Bhutan":       ["/ˈbuːtɑːn/", "不丹", "亚洲", "约3.84万 km²", "约78万"],
    "Brunei":       ["/bruːˈnaɪ/", "文莱", "亚洲", "约5765 km²", "约45万"],
    "Cambodia":     ["/kæmˈboʊdiə/", "柬埔寨", "亚洲", "约18.1万 km²", "约1700万"],
    "China":        ["/ˈtʃaɪnə/", "中国", "亚洲", "约960万 km²", "约14.25亿"],
    "Cyprus":       ["/ˈsaɪprəs/", "塞浦路斯", "亚洲（地理；政制上常归欧洲）", "约9251 km²", "约130万"],
    "East Timor":   ["/ˌiːst ˈtiːmɔːr/", "东帝汶", "亚洲（东南亚，有时归大洋洲）", "约1.5万 km²", "约140万"],
    "Georgia":      ["/ˈdʒɔːrdʒə/", "格鲁吉亚", "亚洲（外高加索，有时归欧洲）", "约6.97万 km²", "约370万"],
    "India":        ["/ˈɪndiə/", "印度", "亚洲", "约298万 km²", "约14.4亿"],
    "Indonesia":    ["/ˌɪndəˈniːʒə/", "印度尼西亚", "亚洲（部分领土在大洋洲）", "约190万 km²", "约2.78亿"],
    "Iran":         ["/ɪˈrɑːn/", "伊朗", "亚洲", "约165万 km²", "约8900万"],
    "Iraq":         ["/ɪˈrɑːk/", "伊拉克", "亚洲", "约43.8万 km²", "约4600万"],
    "Israel":       ["/ˈɪzreɪəl/", "以色列", "亚洲", "约2.2万 km²（含控制区）", "约990万"],
    "Japan":        ["/dʒəˈpæn/", "日本", "亚洲", "约37.8万 km²", "约1.23亿"],
    "Jordan":       ["/ˈdʒɔːrdən/", "约旦", "亚洲", "约8.93万 km²", "约1140万"],
    "Kazakhstan":   ["/ˌkɑːzɑːkˈstæn/", "哈萨克斯坦", "亚洲（乌拉尔河以西一小部在欧洲）", "约272万 km²", "约2000万"],
    "Kuwait":       ["/kʊˈweɪt/", "科威特", "亚洲", "约1.78万 km²", "约430万"],
    "Kyrgyzstan":   ["/ˌɡɪrˈɡɪzstæn/", "吉尔吉斯斯坦", "亚洲", "约20万 km²", "约700万"],
    "Laos":         ["/laʊs/", "老挝", "亚洲", "约23.7万 km²", "约760万"],
    "Lebanon":      ["/ˈlɛbənɒn/", "黎巴嫩", "亚洲", "约1.05万 km²", "约540万"],
    "Malaysia":     ["/məˈleɪʒə/", "马来西亚", "亚洲", "约33.1万 km²", "约3400万"],
    "Maldives":     ["/ˈmɔːldɪvz/", "马尔代夫", "亚洲", "约298 km²", "约52万"],
    "Mongolia":     ["/mɒŋˈɡoʊliə/", "蒙古", "亚洲", "约156万 km²", "约340万"],
    "Myanmar":      ["/ˈmjɑːnmɑːr/", "缅甸", "亚洲", "约67.7万 km²", "约5400万"],
    "Nepal":        ["/nɪˈpɔːl/", "尼泊尔", "亚洲", "约14.7万 km²", "约3050万"],
    "North Korea":  ["/nɔːrθ ˈkɔːriə/", "朝鲜", "亚洲", "约12.3万 km²", "约2600万"],
    "Oman":         ["/oʊˈmɑːn/", "阿曼", "亚洲", "约31万 km²", "约470万"],
    "Pakistan":     ["/ˈpɑːkɪstæn/", "巴基斯坦", "亚洲", "约88.2万 km²（含巴控克什米尔）", "约2.4亿"],
    "Philippines":  ["/ˈfɪlɪpiːnz/", "菲律宾", "亚洲", "约30万 km²", "约1.17亿"],
    "Qatar":        ["/kəˈtɑːr/", "卡塔尔", "亚洲", "约1.16万 km²", "约280万"],
    "Saudi Arabia": ["/ˌsaʊdi əˈreɪbiə/", "沙特阿拉伯", "亚洲", "约215万 km²", "约3700万"],
    "Singapore":    ["/ˌsɪŋəˈpɔːr/", "新加坡", "亚洲", "约733 km²", "约590万"],
    "South Korea":  ["/saʊθ ˈkɔːriə/", "韩国", "亚洲", "约10万 km²", "约5200万"],
    "Sri Lanka":    ["/ʃriː ˈlɑːŋkə/", "斯里兰卡", "亚洲", "约6.56万 km²", "约2200万"],
    "Syria":        ["/ˈsɪriə/", "叙利亚", "亚洲", "约18.5万 km²", "约2300万"],
    "Tajikistan":   ["/təˈdʒiːkɪstæn/", "塔吉克斯坦", "亚洲", "约14.3万 km²", "约1000万"],
    "Thailand":     ["/ˈtaɪlænd/", "泰国", "亚洲", "约51.3万 km²", "约7200万"],
    "Turkey":       ["/ˈtɜːrki/", "土耳其", "亚洲（约97%；西北隅在欧洲）", "约78.4万 km²", "约8580万"],
    "Turkmenistan": ["/ˌtɜːrkməˈnɪstæn/", "土库曼斯坦", "亚洲", "约49.1万 km²", "约630万"],
    "UAE":          ["/juːˌeɪ əˈrɛmɪtʃeɪt/", "阿联酋", "亚洲", "约8.36万 km²", "约950万"],
    "Uzbekistan":   ["/ˌʌzbɛkɪˈstæn/", "乌兹别克斯坦", "亚洲", "约44.7万 km²", "约3500万"],
    "Vietnam":      ["/ˌvjɛtˈnɑːm/", "越南", "亚洲", "约33.1万 km²", "约1亿"],
    "Yemen":        ["/ˈjɛmən/", "也门", "亚洲", "约52.8万 km²", "约3500万"],
    # 观察员国
    "Palestine":    ["/ˈpælstaɪn/", "巴勒斯坦", "亚洲", "约6220 km²（约旦河西岸+加沙）", "约550万"],
    # ---------------- 非洲（54 会员国） ----------------
    "Algeria":      ["/ælˈdʒɪriə/", "阿尔及利亚", "非洲", "约238万 km²", "约4560万"],
    "Angola":       ["/æŋˈɡoʊlə/", "安哥拉", "非洲", "约125万 km²", "约3700万"],
    "Benin":        ["/bɛˈniːn/", "贝宁", "非洲", "约11.5万 km²", "约1370万"],
    "Botswana":     ["/bɒtˈswɑːnə/", "博茨瓦纳", "非洲", "约58.2万 km²", "约270万"],
    "Burkina Faso": ["/ˌbɜːrkiːnə ˈfæsoʊ/", "布基纳法索", "非洲", "约27.4万 km²", "约2300万"],
    "Burundi":      ["/buːˈrʌndi/", "布隆迪", "非洲", "约2.78万 km²", "约1300万"],
    "Cabo Verde":   ["/ˌkɑːboʊ ˈvɛərdi/", "佛得角", "非洲", "约4033 km²", "约57万"],
    "Cameroon":     ["/ˈkæməˈruːn/", "喀麦隆", "非洲", "约47.5万 km²", "约2800万"],
    "Central African Republic": ["/ˌsɛntrəl ˈæfrɪkən/", "中非", "非洲", "约62.3万 km²", "约570万"],
    "Chad":         ["/tʃæd/", "乍得", "非洲", "约128万 km²", "约1940万"],
    "Comoros":      ["/ˈkɒməroʊz/", "科摩罗", "非洲", "约2236 km²", "约89万"],
    "Congo":        ["/ˈkɒŋɡoʊ/", "刚果（布）", "非洲", "约34.2万 km²", "约610万"],
    "Democratic Republic of the Congo": ["/ˌdɛməˈkrætɪk/", "刚果（金）", "非洲", "约234.5万 km²", "约1.04亿"],
    "Côte d'Ivoire": ["/ˌkoʊt dɪˈvɔːr/", "科特迪瓦", "非洲", "约32.2万 km²", "约2900万"],
    "Djibouti":     ["/ˈdʒiːbuːti/", "吉布提", "非洲", "约2.32万 km²", "约110万"],
    "Egypt":        ["/ˈiːdʒɪpt/", "埃及", "非洲（西奈半岛属亚洲）", "约100万 km²", "约1.14亿"],
    "Equatorial Guinea": ["/ˌiːkwəˈtɔːriəl/", "赤道几内亚", "非洲", "约2.81万 km²", "约170万"],
    "Eritrea":      ["/ˌɛrɪˈtreɪə/", "厄立特里亚", "非洲", "约11.8万 km²", "约370万"],
    "Eswatini":     ["/ˌɛswɑːˈtiːni/", "埃斯瓦蒂尼", "非洲", "约1.74万 km²", "约120万"],
    "Ethiopia":     ["/ˌiːθiˈoʊpiə/", "埃塞俄比亚", "非洲", "约110万 km²", "约1.28亿"],
    "Gabon":        ["/ɡəˈbɒn/", "加蓬", "非洲", "约26.8万 km²", "约240万"],
    "Gambia":       ["/ˈɡæmbiə/", "冈比亚", "非洲", "约1.13万 km²", "约280万"],
    "Ghana":        ["/ˈɡɑːnə/", "加纳", "非洲", "约23.9万 km²", "约3400万"],
    "Guinea":       ["/ˈɡɪni/", "几内亚", "非洲", "约24.6万 km²", "约1400万"],
    "Guinea-Bissau": ["/ˌɡɪni bɪˈsaʊ/", "几内亚比绍", "非洲", "约3.61万 km²", "约220万"],
    "Kenya":        ["/ˈkɛnjə/", "肯尼亚", "非洲", "约58万 km²", "约5600万"],
    "Lesotho":      ["/lɛˈsuːtuː/", "莱索托", "非洲", "约3.04万 km²", "约230万"],
    "Liberia":      ["/laɪˈbɪəriə/", "利比里亚", "非洲", "约11.1万 km²", "约550万"],
    "Libya":        ["/ˈlɪbiə/", "利比亚", "非洲", "约176万 km²", "约690万"],
    "Madagascar":   ["/mædəˈɡæskər/", "马达加斯加", "非洲", "约58.7万 km²", "约3100万"],
    "Malawi":       ["/məˈlɑːwiː/", "马拉维", "非洲", "约11.8万 km²", "约2100万"],
    "Mali":         ["/ˈmɑːli/", "马里", "非洲", "约124万 km²", "约2390万"],
    "Mauritania":   ["/ˌmɔːrɪˈteɪniə/", "毛里塔尼亚", "非洲", "约103万 km²", "约490万"],
    "Mauritius":    ["/mɔːˈrɪʃiəs/", "毛里求斯", "非洲", "约2040 km²", "约126万"],
    "Morocco":      ["/məˈrɒkoʊ/", "摩洛哥", "非洲", "约44.7万 km²（不含西撒）", "约3780万"],
    "Mozambique":   ["/moʊˌzæmˈbiːk/", "莫桑比克", "非洲", "约80万 km²", "约3400万"],
    "Namibia":      ["/nəˈmɪbiə/", "纳米比亚", "非洲", "约82.4万 km²", "约260万"],
    "Niger":        ["/naɪˈdʒɛr/", "尼日尔", "非洲", "约127万 km²", "约2700万"],
    "Nigeria":      ["/naɪˈdʒɪəriə/", "尼日利亚", "非洲", "约92.4万 km²", "约2.33亿"],
    "Rwanda":       ["/ruːˈændə/", "卢旺达", "非洲", "约2.63万 km²", "约1450万"],
    "São Tomé and Príncipe": ["/saʊ təˈmeɪ/", "圣多美和普林西比", "非洲", "约964 km²", "约23万"],
    "Senegal":      ["/ˈsɛnɪɡəl/", "塞内加尔", "非洲", "约19.7万 km²", "约1800万"],
    "Seychelles":   ["/seɪˈʃɛlz/", "塞舌尔", "非洲", "约455 km²", "约12万"],
    "Sierra Leone": ["/siˈɛərə liˈoʊn/", "塞拉利昂", "非洲", "约7.23万 km²", "约870万"],
    "Somalia":      ["/soʊˈmɑːliə/", "索马里", "非洲", "约63.8万 km²", "约1850万"],
    "South Africa": ["/saʊθ ˈæfrɪkə/", "南非", "非洲", "约122万 km²", "约6000万"],
    "South Sudan":  ["/saʊθ ˈsuːdæn/", "南苏丹", "非洲", "约62万 km²", "约1110万"],
    "Sudan":        ["/suːˈdæn/", "苏丹", "非洲", "约188万 km²", "约4900万"],
    "Tanzania":     ["/tænˈzæniə/", "坦桑尼亚", "非洲", "约94.5万 km²", "约6860万"],
    "Togo":         ["/ˈtoʊɡoʊ/", "多哥", "非洲", "约5.68万 km²", "约940万"],
    "Tunisia":      ["/tjuːˈniːʒə/", "突尼斯", "非洲", "约16.4万 km²", "约1250万"],
    "Uganda":       ["/juːˈɡændə/", "乌干达", "非洲", "约24.2万 km²", "约4900万"],
    "Zambia":       ["/ˈzæmbiə/", "赞比亚", "非洲", "约75.3万 km²", "约2090万"],
    "Zimbabwe":     ["/zɪmˈbɑːbweɪ/", "津巴布韦", "非洲", "约39.1万 km²", "约1680万"],
    # ---------------- 欧洲（43 会员国） ----------------
    "Albania":      ["/ælˈbeɪniə/", "阿尔巴尼亚", "欧洲", "约2.87万 km²", "约280万"],
    "Andorra":      ["/ænˈdɔːrə/", "安道尔", "欧洲", "约468 km²", "约8万"],
    "Austria":      ["/ˈɔːstriə/", "奥地利", "欧洲", "约8.39万 km²", "约920万"],
    "Belarus":      ["/ˌbɛləˈrus/", "白俄罗斯", "欧洲", "约20.8万 km²", "约920万"],
    "Belgium":      ["/ˈbɛldʒəm/", "比利时", "欧洲", "约3.07万 km²", "约1180万"],
    "Bosnia and Herzegovina": ["/ˈbɒzniə/", "波黑", "欧洲", "约5.12万 km²", "约320万"],
    "Bulgaria":     ["/bʌlˈɡɛəriə/", "保加利亚", "欧洲", "约11.1万 km²", "约640万"],
    "Croatia":      ["/kroʊˈeɪʃə/", "克罗地亚", "欧洲", "约5.66万 km²", "约385万"],
    "Czech Republic": ["/tʃɛk/", "捷克", "欧洲", "约7.89万 km²", "约1090万"],
    "Denmark":      ["/ˈdɛnmɑːrk/", "丹麦", "欧洲（本土；含自治领更大）", "约4.31万 km²（本土）", "约590万"],
    "Estonia":      ["/ɛˈstəniə/", "爱沙尼亚", "欧洲", "约4.53万 km²", "约137万"],
    "Finland":      ["/ˈfɪnlənd/", "芬兰", "欧洲", "约33.8万 km²", "约560万"],
    "France":       ["/fræns/", "法国", "欧洲（含海外大区约64.4万 km²）", "约55.2万 km²（本土）", "约6800万"],
    "Germany":      ["/ˈdʒɜːrməni/", "德国", "欧洲", "约35.8万 km²", "约8450万"],
    "Greece":       ["/ɡriːs/", "希腊", "欧洲", "约13.2万 km²", "约1040万"],
    "Hungary":      ["/ˈhʌŋɡəri/", "匈牙利", "欧洲", "约9.3万 km²", "约960万"],
    "Iceland":      ["/ˈaɪslənd/", "冰岛", "欧洲", "约10.3万 km²", "约39万"],
    "Ireland":      ["/ˈaɪərlənd/", "爱尔兰", "欧洲", "约7.03万 km²", "约530万"],
    "Italy":        ["/ˈɪtəli/", "意大利", "欧洲", "约30.1万 km²", "约5890万"],
    "Latvia":       ["/ˈlætviə/", "拉脱维亚", "欧洲", "约6.46万 km²", "约188万"],
    "Liechtenstein": ["/ˈlɪktənstaɪn/", "列支敦士登", "欧洲", "约160 km²", "约4万"],
    "Lithuania":    ["/ˌlɪθjuˈeɪniə/", "立陶宛", "欧洲", "约6.53万 km²", "约289万"],
    "Luxembourg":   ["/ˈlʌksəmbɜːrɡ/", "卢森堡", "欧洲", "约2586 km²", "约67万"],
    "Malta":        ["/ˈmɔːltə/", "马耳他", "欧洲", "约316 km²", "约54万"],
    "Moldova":      ["/ˈmɒldəvə/", "摩尔多瓦", "欧洲", "约3.38万 km²", "约250万"],
    "Monaco":       ["/ˈmɒnəkoʊ/", "摩纳哥", "欧洲", "约2.08 km²", "约3.7万"],
    "Montenegro":   ["/ˌmɒntɪˈneɪɡroʊ/", "黑山", "欧洲", "约1.39万 km²", "约62万"],
    "Netherlands":  ["/ˈnɛðərləndz/", "荷兰", "欧洲（本土）", "约4.15万 km²（本土）", "约1800万"],
    "North Macedonia": ["/nɔːrθ məˈsidoʊniə/", "北马其顿", "欧洲", "约2.57万 km²", "约180万"],
    "Norway":       ["/ˈnɔːrweɪ/", "挪威", "欧洲", "约38.5万 km²（本土）", "约560万"],
    "Poland":       ["/ˈpoʊlənd/", "波兰", "欧洲", "约31.3万 km²", "约3670万"],
    "Portugal":     ["/ˈpɔːrtuɡəl/", "葡萄牙", "欧洲", "约9.22万 km²", "约1050万"],
    "Romania":      ["/roʊˈmeɪniə/", "罗马尼亚", "欧洲", "约23.8万 km²", "约1900万"],
    "Russia":       ["/ˈrʌʃə/", "俄罗斯", "欧洲（地跨欧亚，首都偏欧）", "约1710万 km²", "约1.44亿"],
    "San Marino":   ["/ˌsæn məˈriːnoʊ/", "圣马力诺", "欧洲", "约61 km²", "约3.4万"],
    "Serbia":       ["/ˈsɜːrbiə/", "塞尔维亚", "欧洲", "约7.75万 km²（不含科索沃）", "约660万"],
    "Slovakia":     ["/sloʊˈvækiə/", "斯洛伐克", "欧洲", "约4.9万 km²", "约540万"],
    "Slovenia":     ["/sloʊˈviːniə/", "斯洛文尼亚", "欧洲", "约2.03万 km²", "约210万"],
    "Spain":        ["/speɪn/", "西班牙", "欧洲", "约50.6万 km²", "约4830万"],
    "Sweden":       ["/ˈswiːdɪn/", "瑞典", "欧洲", "约45万 km²", "约1050万"],
    "Switzerland":  ["/ˈswɪtsərlənd/", "瑞士", "欧洲", "约4.13万 km²", "约890万"],
    "Ukraine":      ["/juːˈkreɪn/", "乌克兰", "欧洲", "约60.4万 km²", "约3700万（含出境人口波动）"],
    "United Kingdom": ["/juːˈnaɪtɪd ˈkɪŋdəm/", "英国", "欧洲", "约24.4万 km²", "约6800万"],
    # 观察员国
    "Vatican":      ["/ˈvætɪkən/", "梵蒂冈", "欧洲", "约0.44 km²", "约800人"],
    # ---------------- 北美洲与加勒比（23 会员国） ----------------
    "Antigua and Barbuda": ["/ænˈtiːɡə/", "安提瓜和巴布达", "北美洲", "约443 km²", "约9.4万"],
    "The Bahamas":  ["/bəˈhæməz/", "巴哈马", "北美洲", "约1.4万 km²", "约40万"],
    "Barbados":     ["/bɑːrˈbeɪdoʊz/", "巴巴多斯", "北美洲", "约439 km²", "约28万"],
    "Belize":       ["/bəˈliːz/", "伯利兹", "北美洲", "约2.3万 km²", "约41万"],
    "Canada":       ["/ˈkænədə/", "加拿大", "北美洲", "约998万 km²", "约4100万"],
    "Costa Rica":   ["/ˌkɒstə ˈriːkə/", "哥斯达黎加", "北美洲", "约5.11万 km²", "约520万"],
    "Cuba":         ["/ˈkjuːbə/", "古巴", "北美洲", "约11万 km²", "约1110万"],
    "Dominica":     ["/ˌdɒmɪˈniːkə/", "多米尼克", "北美洲", "约751 km²", "约6.7万"],
    "Dominican Republic": ["/dəˈmɪnɪkən/", "多米尼加", "北美洲", "约4.87万 km²", "约1130万"],
    "El Salvador":  ["/ɛl səˈlvədɔːr/", "萨尔瓦多", "北美洲", "约2.1万 km²", "约640万"],
    "Grenada":      ["/ɡrɪˈnædə/", "格林纳达", "北美洲", "约344 km²", "约12.6万"],
    "Guatemala":    ["/ˌɡwɑːtəˈmɑːlə/", "危地马拉", "北美洲", "约10.9万 km²", "约1790万"],
    "Haiti":        ["/ˈheɪti/", "海地", "北美洲", "约2.78万 km²", "约1170万"],
    "Honduras":     ["/hɒnˈdjʊərəs/", "洪都拉斯", "北美洲", "约11.2万 km²", "约1060万"],
    "Jamaica":      ["/dʒəˈmeɪkə/", "牙买加", "北美洲", "约1.1万 km²", "约280万"],
    "Mexico":       ["/ˈmɛksɪkoʊ/", "墨西哥", "北美洲", "约196万 km²", "约1.29亿"],
    "Nicaragua":    ["/ˌnɪkəˈrɑːɡwə/", "尼加拉瓜", "北美洲", "约13万 km²", "约700万"],
    "Panama":       ["/ˈpænəmə/", "巴拿马", "北美洲（连接南美的地峡国）", "约7.55万 km²", "约450万"],
    "Saint Kitts and Nevis": ["/seɪnt kɪts/", "圣基茨和尼维斯", "北美洲", "约261 km²", "约4.8万"],
    "Saint Lucia":  ["/seɪnt ˈluːʃə/", "圣卢西亚", "北美洲", "约617 km²", "约18.1万"],
    "Saint Vincent and the Grenadines": ["/vɪnˈsɛnt/", "圣文森特和格林纳丁斯", "北美洲", "约389 km²", "约4.5万"],
    "Trinidad and Tobago": ["/ˈtrɪnɪdæd/", "特立尼达和多巴哥", "北美洲", "约5130 km²", "约153万"],
    "United States": ["/juːˈnaɪtɪd steɪts/", "美国", "北美洲", "约983万 km²", "约3.4亿"],
    # ---------------- 南美洲（12 会员国） ----------------
    "Argentina":    ["/ˌɑːrdʒənˈtiːnə/", "阿根廷", "南美洲", "约278万 km²", "约4660万"],
    "Bolivia":      ["/bəˈlɪviə/", "玻利维亚", "南美洲", "约110万 km²", "约1240万"],
    "Brazil":       ["/brəˈzɪl/", "巴西", "南美洲", "约851万 km²", "约2.17亿"],
    "Chile":        ["/ˈtʃɪleɪ/", "智利", "南美洲", "约75.6万 km²", "约2000万"],
    "Colombia":     ["/kəˈlʌmbiə/", "哥伦比亚", "南美洲", "约114万 km²", "约5290万"],
    "Ecuador":      ["/ˈɛkwədɔːr/", "厄瓜多尔", "南美洲", "约25.6万 km²", "约1830万"],
    "Guyana":       ["/ɡaɪˈænə/", "圭亚那", "南美洲", "约21.5万 km²", "约84万"],
    "Paraguay":     ["/ˈpærəɡweɪ/", "巴拉圭", "南美洲", "约40.7万 km²", "约680万"],
    "Peru":         ["/pəˈruː/", "秘鲁", "南美洲", "约128.5万 km²", "约3440万"],
    "Suriname":     ["/ˈsʊərɪnæm/", "苏里南", "南美洲", "约16.4万 km²", "约63万"],
    "Uruguay":      ["/ˈjʊərəɡweɪ/", "乌拉圭", "南美洲", "约17.6万 km²", "约340万"],
    "Venezuela":    ["/ˌvɛnzəˈweɪlə/", "委内瑞拉", "南美洲", "约91.6万 km²", "约2840万"],
    # ---------------- 大洋洲（14 会员国） ----------------
    "Australia":    ["/ɔːˈstreɪliə/", "澳大利亚", "大洋洲", "约769万 km²", "约2700万"],
    "Fiji":         ["/ˈfiːdʒi/", "斐济", "大洋洲", "约1.83万 km²", "约93万"],
    "Kiribati":     ["/ˌkɪrɪˈbɑːsti/", "基里巴斯", "大洋洲", "约811 km²", "约13万"],
    "Marshall Islands": ["/ˈmɑːrʃəl/", "马绍尔群岛", "大洋洲", "约181 km²", "约4.2万"],
    "Micronesia":   ["/ˌmaɪkrəˈniːʒə/", "密克罗尼西亚联邦", "大洋洲", "约702 km²", "约11.5万"],
    "Nauru":        ["/nɔːˈruː/", "瑙鲁", "大洋洲", "约21 km²", "约1.2万"],
    "New Zealand":  ["/ˈnjuː ziːlənd/", "新西兰", "大洋洲", "约26.8万 km²", "约530万"],
    "Palau":        ["/pəˈlaʊ/", "帕劳", "大洋洲", "约459 km²", "约1.8万"],
    "Papua New Guinea": ["/ˈpɑːpuə/", "巴布亚新几内亚", "大洋洲", "约46.3万 km²", "约1030万"],
    "Samoa":        ["/səˈmoʊə/", "萨摩亚", "大洋洲", "约2944 km²", "约22万"],
    "Solomon Islands": ["/ˈsɒləmən/", "所罗门群岛", "大洋洲", "约2.9万 km²", "约74万"],
    "Tonga":        ["/ˈtɒŋɡə/", "汤加", "大洋洲", "约748 km²", "约10.4万"],
    "Tuvalu":       ["/ˌtuːˈvɑːluː/", "图瓦卢", "大洋洲", "约26 km²", "约1.1万"],
    "Vanuatu":      ["/ˌvɑːnuˈɑːtuː/", "瓦努阿图", "大洋洲", "约1.22万 km²", "约33万"],

    # ---------- 海外领地 / 王权属地 / 非联合国会员地区（键名 = 地图返回名） ----------
    # 面积、人口为常用公开口径约数；"大洲"字段标注政治归属身份。
    "Aland":                    ["/ˈɒlənd/", "奥兰群岛", "欧洲（芬兰自治省）", "约6800 km²", "约3万"],
    "American Samoa":           ["/əˈmɛrɪkən səˈmoʊə/", "美属萨摩亚", "大洋洲（美国属地）", "约200 km²", "约4.6万"],
    "Bermuda":                  ["/bərˈmjuːdə/", "百慕大", "北美洲（英国海外领地）", "约54 km²", "约6.5万"],
    "Br. Indian Ocean Ter.":    ["/ˌɪndiən ˈoʊʃən/", "英属印度洋领地", "非洲（英国海外领地；主权争议）", "约60 km²", "无常住平民"],
    "Cayman Is.":               ["/ˈkeɪmən/", "开曼群岛", "北美洲（英国海外领地）", "约264 km²", "约6.9万"],
    "Curaçao":                  ["/kjʊˈra.saʊ/", "库拉索", "南美洲（荷兰构成国）", "约444 km²", "约15万"],
    "Faeroe Is.":               ["/ˈfɛroʊ/", "法罗群岛", "欧洲（丹麦自治领地）", "约1400 km²", "约5.4万"],
    "Falkland Is.":             ["/ˈfɔːklənd/", "福克兰群岛（马尔维纳斯群岛）", "南美洲（英国海外领地；阿根廷主张主权）", "约1.22万 km²", "约3700"],
    "Fr. Polynesia":            ["/ˌfrɛntʃ pɒlɪˈniːʒə/", "法属波利尼西亚", "大洋洲（法国海外集体）", "约4167 km²", "约28万"],
    "Fr. S. Antarctic Lands":   ["/ˌsʌθ æntˈɑːrktɪk/", "法属南部和南极领地", "非洲／南极（法国海外领地）", "约778万 km²（含南极主张区）", "无常住（轮换科考）"],
    "Greenland":                ["/ˈɡriːnlənd/", "格陵兰", "北美洲（丹麦自治领地）", "约216万 km²", "约5.6万"],
    "Guam":                     ["/ɡwɑːm/", "关岛", "大洋洲（美国属地）", "约549 km²", "约17万"],
    "Heard I. and McDonald Is.": ["/hɜːrd/", "赫德岛和麦克唐纳群岛", "南极（澳大利亚领地）", "约372 km²", "无常住"],
    "Isle of Man":              ["/aɪl əv mæn/", "马恩岛", "欧洲（英国王权属地）", "约572 km²", "约8.5万"],
    "Jersey":                   ["/ˈdʒɜːrzi/", "泽西", "欧洲（英国王权属地）", "约118 km²", "约11万"],
    "Montserrat":               ["/ˌmɒntsəˈræt/", "蒙特塞拉特", "北美洲（英国海外领地）", "约102 km²", "约0.5万"],
    "N. Cyprus":                ["/nɔːrθ ˈsaɪprəs/", "北塞浦路斯", "亚洲（单方面宣布独立，仅土耳其承认）", "约3355 km²", "约39万"],
    "N. Mariana Is.":           ["/ˌnɔːrθ məˈriːɑːnə/", "北马里亚纳群岛", "大洋洲（美国自治邦）", "约464 km²", "约4.7万"],
    "New Caledonia":            ["/ˌnuː kælɪˈdoʊniə/", "新喀里多尼亚", "大洋洲（法国特殊集体）", "约1.86万 km²", "约29万"],
    "Niue":                     ["/ˈnjuːeɪ/", "纽埃", "大洋洲（新西兰自由联系国，非联合国会员）", "约260 km²", "约0.17万"],
    "Puerto Rico":              ["/ˌpwɛrtoʊ ˈriːkoʊ/", "波多黎各", "北美洲（美国自治邦）", "约9104 km²", "约320万"],
    "S. Geo. and S. Sandw. Is.": ["/ˌsaʊθ dʒɔːrdʒiə/", "南乔治亚和南桑威奇群岛", "南美洲／南极（英国海外领地）", "约3903 km²", "无常住（科研）"],
    "Saint Helena":             ["/seɪnt həˈliːnə/", "圣赫勒拿、阿森松和特里斯坦-达库尼亚", "非洲（英国海外领地）", "约122 km²", "约5400"],
    "Siachen Glacier":          ["/siˈɑːtʃən/", "锡亚琴冰川", "亚洲（印巴争议无人区）", "约3000 km²", "无常住平民"],
    "St. Pierre and Miquelon":  ["/ˌpjɛər miːkləˈnɒn/", "圣皮埃尔和密克隆", "北美洲（法国海外集体）", "约242 km²", "约5800"],
    "Turks and Caicos Is.":     ["/ˈtɜːrks/", "特克斯和凯科斯群岛", "北美洲（英国海外领地）", "约948 km²", "约4.6万"],
    "U.S. Virgin Is.":          ["/ˌviːrdʒɪn ˈaɪləndz/", "美属维尔京群岛", "北美洲（美国属地）", "约346 km²", "约10.6万"],
    "W. Sahara":                ["/ˈsɑːhɑːrə/", "西撒哈拉", "非洲（非自治领土；主权争议）", "约26.6万 km²", "约60万（估算）"],
}

# 别名映射：世界地图数据中同一国家可能使用的其他名称写法 -> 规范键
aliases = {
    "USA": "United States",
    "United States of America": "United States",
    "Republic of Korea": "South Korea",
    "Korea": "South Korea",
    "Dem. Rep. Korea": "North Korea",
    "Dem. People's Rep. Korea": "North Korea",
    "Czechia": "Czech Republic",
    "Czech Rep.": "Czech Republic",
    "Russian Federation": "Russia",
    "Iran (Islamic Republic of)": "Iran",
    "Islamic Republic of Iran": "Iran",
    "Syrian Arab Republic": "Syria",
    "Lao People's Democratic Republic": "Laos",
    "Viet Nam": "Vietnam",
    "Brunei Darussalam": "Brunei",
    "Bahamas": "The Bahamas",
    "Bosnia and Herz.": "Bosnia and Herzegovina",
    "Central African Rep.": "Central African Republic",
    "Congo Rep.": "Congo",
    "Republic of the Congo": "Congo",
    "Rep. Congo": "Congo",
    "Dem. Rep. Congo": "Democratic Republic of the Congo",
    "Congo (Dem. Rep.)": "Democratic Republic of the Congo",
    "Congo-Kinshasa": "Democratic Republic of the Congo",
    "Ivory Coast": "Côte d'Ivoire",
    "Cote D'Ivoire": "Côte d'Ivoire",
    "Dominican Rep.": "Dominican Republic",
    "Eq. Guinea": "Equatorial Guinea",
    "S. Sudan": "South Sudan",
    "Solomon Is.": "Solomon Islands",
    "Timor-Leste": "East Timor",
    "Swaziland": "Eswatini",
    "eSwatini": "Eswatini",
    "Macedonia": "North Macedonia",
    "FYROM": "North Macedonia",
    "Türkiye": "Turkey",
    "United Republic of Tanzania": "Tanzania",
    "Federated States of Micronesia": "Micronesia",
    "Marshall Is.": "Marshall Islands",
    "St. Kitts and Nevis": "Saint Kitts and Nevis",
    "St. Lucia": "Saint Lucia",
    "St. Vincent and the Grenadines": "Saint Vincent and the Grenadines",
    "Saint Vincent": "Saint Vincent and the Grenadines",
    "Sao Tome and Principe": "São Tomé and Príncipe",
    "Sao Tomé and Príncipe": "São Tomé and Príncipe",
    "Cape Verde": "Cabo Verde",
    "Kyrgyz Republic": "Kyrgyzstan",
    "Burma": "Myanmar",
    "United Arab Emirates": "UAE",
    "West Bank and Gaza": "Palestine",
    "Vatican City": "Vatican",
    "Holy See": "Vatican",
    "Lao PDR": "Laos",
    "Antigua and Barb.": "Antigua and Barbuda",
    "St. Vin. and Gren.": "Saint Vincent and the Grenadines",
    "São Tomé and Principe": "São Tomé and Príncipe",
}
for _alias, _key in aliases.items():
    if _key in country_info:
        country_info[_alias] = country_info[_key]

# 首都（中英+英文音标）与英文缩写（ISO 3166-1 alpha-2）：规范名 -> [第6项首都, 第7项缩写]
# 非会员地区用"行政中心"表述；主权争议只作事实标注，不判归属。
capital_abbr = {
    # ---------- 亚洲 ----------
    "Afghanistan": ["首都：喀布尔 Kabul /kəˈbuːl/", "缩写：AF"],
    "Armenia": ["首都：埃里温 Yerevan /ˈjɛrɪvæn/", "缩写：AM"],
    "Azerbaijan": ["首都：巴库 Baku /ˈbɑːkuː/", "缩写：AZ"],
    "Bahrain": ["首都：麦纳麦 Manama /mæˈnɑːmeɪ/", "缩写：BH"],
    "Bangladesh": ["首都：达卡 Dhaka /ˈdɑːkə/", "缩写：BD"],
    "Bhutan": ["首都：廷布 Thimphu /ˈtɪmpuː/", "缩写：BT"],
    "Brunei": ["首都：斯里巴加湾市 Bandar Seri Begawan /ˌbændər ˈsriː bəˈɡɑːwɑːn/", "缩写：BN"],
    "Cambodia": ["首都：金边 Phnom Penh /ˌnɒm ˈpɛnʔ/", "缩写：KH"],
    "China": ["首都：北京 Beijing /ˌbeɪˈdʒɪŋ/", "缩写：CN"],
    "Cyprus": ["首都：尼科西亚 Nicosia /nɪˈkoʊʃə/", "缩写：CY"],
    "East Timor": ["首都：帝力 Dili /ˈdiːli/", "缩写：TL"],
    "Georgia": ["首都：第比利斯 Tbilisi /təˈbiːlɪsi/", "缩写：GE"],
    "India": ["首都：新德里 New Delhi /ˌnjuː ˈdɛli/", "缩写：IN"],
    "Indonesia": ["首都：雅加达 Jakarta /dʒəˈkɑːrtə/（新首都努山塔拉在建）", "缩写：ID"],
    "Iran": ["首都：德黑兰 Tehran /tɛˈrɑːn/", "缩写：IR"],
    "Iraq": ["首都：巴格达 Baghdad /ˈbæɡdæd/", "缩写：IQ"],
    "Israel": ["首都：耶路撒冷 Jerusalem /dʒəˈruːzələm/（声明；多数国家使馆设于特拉维夫）", "缩写：IL"],
    "Japan": ["首都：东京 Tokyo /ˈtoʊkjoʊ/", "缩写：JP"],
    "Jordan": ["首都：安曼 Amman /əˈmæn/", "缩写：JO"],
    "Kazakhstan": ["首都：阿斯塔纳 Astana /əˈstɑːnə/", "缩写：KZ"],
    "Kuwait": ["首都：科威特城 Kuwait City /kʊˈweɪt ˈsɪti/", "缩写：KW"],
    "Kyrgyzstan": ["首都：比什凯克 Bishkek /bɪʃˈkɛk/", "缩写：KG"],
    "Laos": ["首都：万象 Vientiane /vjɛnˈtjæn/", "缩写：LA"],
    "Lebanon": ["首都：贝鲁特 Beirut /beɪˈruːt/", "缩写：LB"],
    "Malaysia": ["首都：吉隆坡 Kuala Lumpur /ˌkuːələ ˈlʊmpʊər/（行政中心布城 Putrajaya）", "缩写：MY"],
    "Maldives": ["首都：马累 Malé /məˈleɪ/", "缩写：MV"],
    "Mongolia": ["首都：乌兰巴托 Ulaanbaatar /ˌuːlɑːnˈbɑːtər/", "缩写：MN"],
    "Myanmar": ["首都：内比都 Naypyidaw /ˌnaɪpɪˈdɔː/", "缩写：MM"],
    "Nepal": ["首都：加德满都 Kathmandu /ˌkɑːtmɑːnˈduː/", "缩写：NP"],
    "North Korea": ["首都：平壤 Pyongyang /ˌpjɒŋˈjɑːŋ/", "缩写：KP"],
    "Oman": ["首都：马斯喀特 Muscat /ˈmʌskæt/", "缩写：OM"],
    "Pakistan": ["首都：伊斯兰堡 Islamabad /ɪsˈlɑːməbɑːd/", "缩写：PK"],
    "Philippines": ["首都：马尼拉 Manila /məˈnɪlə/", "缩写：PH"],
    "Qatar": ["首都：多哈 Doha /ˈdoʊhə/", "缩写：QA"],
    "Saudi Arabia": ["首都：利雅得 Riyadh /rɪˈɑːd/", "缩写：SA"],
    "Singapore": ["首都：新加坡市 Singapore City（城邦国家）", "缩写：SG"],
    "South Korea": ["首都：首尔 Seoul /soʊl/", "缩写：KR"],
    "Sri Lanka": ["首都：科伦坡 Colombo /kəˈlʌmbəʊ/（行政首都斯里贾亚瓦德纳普拉科特）", "缩写：LK"],
    "Syria": ["首都：大马士革 Damascus /dəˈmæskəs/", "缩写：SY"],
    "Tajikistan": ["首都：杜尚别 Dushanbe /dʊˈʃɑːmbɛ/", "缩写：TJ"],
    "Thailand": ["首都：曼谷 Bangkok /ˈbæŋkɒk/", "缩写：TH"],
    "Turkey": ["首都：安卡拉 Ankara /ˈæŋkərə/", "缩写：TR"],
    "Turkmenistan": ["首都：阿什哈巴德 Ashgabat /ˈæʃɡəbæt/", "缩写：TM"],
    "UAE": ["首都：阿布扎比 Abu Dhabi /ˌɑːbuː ˈdɑːbi/", "缩写：AE"],
    "Uzbekistan": ["首都：塔什干 Tashkent /ˈtæʃkɛnt/", "缩写：UZ"],
    "Vietnam": ["首都：河内 Hanoi /həˈnɔɪ/", "缩写：VN"],
    "Yemen": ["首都：萨那 Sana'a /ˌsɑːnəˈɑː/", "缩写：YE"],
    "Palestine": ["首都：东耶路撒冷 East Jerusalem（声明；实际行政中心拉姆安拉 Ramallah /ˌræməˈlɑː/）", "缩写：PS"],
    # ---------- 非洲 ----------
    "Algeria": ["首都：阿尔及尔 Algiers /ælˈdʒɪrz/", "缩写：DZ"],
    "Angola": ["首都：罗安达 Luanda /luːˈɑːndə/", "缩写：AO"],
    "Benin": ["首都：波多诺伏 Porto-Novo /ˌpɔːrtoʊ ˈnoʊvoʊ/（政府驻地科托努）", "缩写：BJ"],
    "Botswana": ["首都：哈博罗内 Gaborone /ˌɡæbəˈroʊneɪ/", "缩写：BW"],
    "Burkina Faso": ["首都：瓦加杜古 Ouagadougou /wɑːˌɡɑːˈduːɡuː/", "缩写：BF"],
    "Burundi": ["首都：吉特加 Gitega /ɡɪˈtɛɡə/", "缩写：BI"],
    "Cabo Verde": ["首都：普拉亚 Praia /ˈpraɪə/", "缩写：CV"],
    "Cameroon": ["首都：雅温得 Yaoundé /ˈjaʊndeɪ/", "缩写：CM"],
    "Central African Republic": ["首都：班吉 Bangui /ˈbæŋɡi/", "缩写：CF"],
    "Chad": ["首都：恩贾梅纳 N'Djamena /ɛnˈdʒæmɪnə/", "缩写：TD"],
    "Comoros": ["首都：莫罗尼 Moroni /moˈroʊni/", "缩写：KM"],
    "Congo": ["首都：布拉柴维尔 Brazzaville /ˌbræsəˈvɪl/", "缩写：CG"],
    "Democratic Republic of the Congo": ["首都：金沙萨 Kinshasa /kɪnˈʃæsə/", "缩写：CD"],
    "Côte d'Ivoire": ["首都：亚穆苏克罗 Yamoussoukro /ˌjæmuːˈsuːkroʊ/（政府驻地阿比让）", "缩写：CI"],
    "Djibouti": ["首都：吉布提市 Djibouti /dʒɪˈbuːti/", "缩写：DJ"],
    "Egypt": ["首都：开罗 Cairo /ˈkaɪroʊ/", "缩写：EG"],
    "Equatorial Guinea": ["首都：马拉博 Malabo /məˈlɑːboʊ/", "缩写：GQ"],
    "Eritrea": ["首都：阿斯马拉 Asmara /æzˈmɑːrə/", "缩写：ER"],
    "Eswatini": ["首都：姆巴巴内 Mbabane /ɪmˈbɑːbɑːneɪ/（行政；立法兰巴）", "缩写：SZ"],
    "Ethiopia": ["首都：亚的斯亚贝巴 Addis Ababa /ˌædɪs ˈæbəbə/", "缩写：ET"],
    "Gabon": ["首都：利伯维尔 Libreville /liːbrəˈvɪl/", "缩写：GA"],
    "Gambia": ["首都：班珠尔 Banjul /ˈbændʒuːl/", "缩写：GM"],
    "Ghana": ["首都：阿克拉 Accra /əˈkrɑː/", "缩写：GH"],
    "Guinea": ["首都：科纳克里 Conakry /ˈkɒnəkreɪ/", "缩写：GN"],
    "Guinea-Bissau": ["首都：比绍 Bissau /bɪˈsaʊ/", "缩写：GW"],
    "Kenya": ["首都：内罗毕 Nairobi /naɪˈroʊbi/", "缩写：KE"],
    "Lesotho": ["首都：马塞卢 Maseru /mɑːˈsɛruː/", "缩写：LS"],
    "Liberia": ["首都：蒙罗维亚 Monrovia /mɒnˈroʊviə/", "缩写：LR"],
    "Libya": ["首都：的黎波里 Tripoli /ˈtrɪpəli/", "缩写：LY"],
    "Madagascar": ["首都：塔那那利佛 Antananarivo /əˌnæntəˈnɑːrɪvuː/", "缩写：MG"],
    "Malawi": ["首都：利隆圭 Lilongwe /lɪˈlɒŋɡweɪ/", "缩写：MW"],
    "Mali": ["首都：巴马科 Bamako /ˈbæməkoʊ/", "缩写：ML"],
    "Mauritania": ["首都：努瓦克肖特 Nouakchott /nuːækˈʃɒt/", "缩写：MR"],
    "Mauritius": ["首都：路易港 Port Louis /pɔːrt ˈluːi/", "缩写：MU"],
    "Morocco": ["首都：拉巴特 Rabat /rəˈbɑːt/", "缩写：MA"],
    "Mozambique": ["首都：马普托 Maputo /məˈpuːtoʊ/", "缩写：MZ"],
    "Namibia": ["首都：温得和克 Windhoek /ˈvɪndhʊk/", "缩写：NA"],
    "Niger": ["首都：尼亚美 Niamey /niˈɑːmeɪ/", "缩写：NE"],
    "Nigeria": ["首都：阿布贾 Abuja /əˈbuːdʒə/", "缩写：NG"],
    "Rwanda": ["首都：基加利 Kigali /kɪˈɡɑːli/", "缩写：RW"],
    "São Tomé and Príncipe": ["首都：圣多美 São Tomé /saʊ təˈmeɪ/", "缩写：ST"],
    "Senegal": ["首都：达喀尔 Dakar /dəˈkɑːr/", "缩写：SN"],
    "Seychelles": ["首都：维多利亚 Victoria /vɪkˈtɔːriə/", "缩写：SC"],
    "Sierra Leone": ["首都：弗里敦 Freetown /ˈfriːtaʊn/", "缩写：SL"],
    "Somalia": ["首都：摩加迪沙 Mogadishu /moʊɡˈdɪʃuː/", "缩写：SO"],
    "South Africa": ["首都：比勒陀利亚 Pretoria /prɪˈtɔːriə/（行政；立法开普敦、司法布隆方丹）", "缩写：ZA"],
    "South Sudan": ["首都：朱巴 Juba /ˈdʒuːbə/", "缩写：SS"],
    "Sudan": ["首都：喀土穆 Khartoum /kɑːrˈtuːm/", "缩写：SD"],
    "Tanzania": ["首都：多多马 Dodoma /dɒˈdəʊmə/（经济中心达累斯萨拉姆）", "缩写：TZ"],
    "Togo": ["首都：洛美 Lomé /loʊˈmeɪ/", "缩写：TG"],
    "Tunisia": ["首都：突尼斯市 Tunis /ˈtjuːnɪs/", "缩写：TN"],
    "Uganda": ["首都：坎帕拉 Kampala /kæmˈpɑːlə/", "缩写：UG"],
    "Zambia": ["首都：卢萨卡 Lusaka /luːˈsɑːkə/", "缩写：ZM"],
    "Zimbabwe": ["首都：哈拉雷 Harare /həˈrɑːreɪ/", "缩写：ZW"],
    # ---------- 欧洲 ----------
    "Albania": ["首都：地拉那 Tirana /tɪˈrɑːnə/", "缩写：AL"],
    "Andorra": ["首都：安道尔城 Andorra la Vella /ˌændɔːrə lə ˈvɛjə/", "缩写：AD"],
    "Austria": ["首都：维也纳 Vienna /viˈɛnə/", "缩写：AT"],
    "Belarus": ["首都：明斯克 Minsk /mɪnsk/", "缩写：BY"],
    "Belgium": ["首都：布鲁塞尔 Brussels /ˈbrʌsəlz/", "缩写：BE"],
    "Bosnia and Herzegovina": ["首都：萨拉热窝 Sarajevo /ˌsɑːrəˈjeɪvoʊ/", "缩写：BA"],
    "Bulgaria": ["首都：索非亚 Sofia /ˈsoʊfiə/", "缩写：BG"],
    "Croatia": ["首都：萨格勒布 Zagreb /ˈzæɡrɛb/", "缩写：HR"],
    "Czech Republic": ["首都：布拉格 Prague /prɑːɡ/", "缩写：CZ"],
    "Denmark": ["首都：哥本哈根 Copenhagen /ˌkoʊpənˈheɪɡən/", "缩写：DK"],
    "Estonia": ["首都：塔林 Tallinn /ˈtælɪn/", "缩写：EE"],
    "Finland": ["首都：赫尔辛基 Helsinki /hɛlˈsɪŋki/", "缩写：FI"],
    "France": ["首都：巴黎 Paris /ˈpærɪs/", "缩写：FR"],
    "Germany": ["首都：柏林 Berlin /bɜːrlɪn/", "缩写：DE"],
    "Greece": ["首都：雅典 Athens /ˈæθɪnz/", "缩写：GR"],
    "Hungary": ["首都：布达佩斯 Budapest /ˈbudəpɛst/", "缩写：HU"],
    "Iceland": ["首都：雷克雅未克 Reykjavík /ˈreɪkjəvɪk/", "缩写：IS"],
    "Ireland": ["首都：都柏林 Dublin /ˈdʌblɪn/", "缩写：IE"],
    "Italy": ["首都：罗马 Rome /roʊm/", "缩写：IT"],
    "Latvia": ["首都：里加 Riga /ˈriːɡə/", "缩写：LV"],
    "Liechtenstein": ["首都：瓦杜兹 Vaduz /vəˈdʊts/", "缩写：LI"],
    "Lithuania": ["首都：维尔纽斯 Vilnius /ˈvɪlniəs/", "缩写：LT"],
    "Luxembourg": ["首都：卢森堡市 Luxembourg /ˌlʌksəmˈbɜːrɡ/", "缩写：LU"],
    "Malta": ["首都：瓦莱塔 Valletta /vəˈlɛtə/", "缩写：MT"],
    "Moldova": ["首都：基希讷乌 Chișinău /ˌkɪʃɪˈnaʊ/", "缩写：MD"],
    "Monaco": ["首都：摩纳哥 Monaco /ˈmɒnəkoʊ/（城邦）", "缩写：MC"],
    "Montenegro": ["首都：波德戈里察 Podgorica /poʊdˈɡɔːrɪtsə/", "缩写：ME"],
    "Netherlands": ["首都：阿姆斯特丹 Amsterdam /ˌæmstərˈdæm/（政府驻地海牙）", "缩写：NL"],
    "North Macedonia": ["首都：斯科普里 Skopje /ˈskoʊpjɛ/", "缩写：MK"],
    "Norway": ["首都：奥斯陆 Oslo /ˈɒzloʊ/", "缩写：NO"],
    "Poland": ["首都：华沙 Warsaw /ˈwɔːrsɑː/", "缩写：PL"],
    "Portugal": ["首都：里斯本 Lisbon /lɪzˈbɒn/", "缩写：PT"],
    "Romania": ["首都：布加勒斯特 Bucharest /ˌbuːkəˈrɛst/", "缩写：RO"],
    "Russia": ["首都：莫斯科 Moscow /ˈmɒskaʊ/", "缩写：RU"],
    "San Marino": ["首都：圣马力诺市 San Marino /ˌsɑːn məˈriːnoʊ/", "缩写：SM"],
    "Serbia": ["首都：贝尔格莱德 Belgrade /ˈbɛlɡreɪd/", "缩写：RS"],
    "Slovakia": ["首都：布拉迪斯拉发 Bratislava /ˌbrætɪslˈɑːvə/", "缩写：SK"],
    "Slovenia": ["首都：卢布尔雅那 Ljubljana /luːbljˈɑːnə/", "缩写：SI"],
    "Spain": ["首都：马德里 Madrid /məˈdrɪd/", "缩写：ES"],
    "Sweden": ["首都：斯德哥尔摩 Stockholm /ˈstɒkhoʊlm/", "缩写：SE"],
    "Switzerland": ["首都：伯尔尼 Bern /bɜːrn/（联邦城市）", "缩写：CH"],
    "Ukraine": ["首都：基辅 Kyiv /ˈkiːɪv/", "缩写：UA"],
    "United Kingdom": ["首都：伦敦 London /ˈlʌndən/", "缩写：GB"],
    "Vatican": ["首都：梵蒂冈城 Vatican City /ˌvætɪkən ˈsɪti/（城邦）", "缩写：VA"],
    # ---------- 北美洲与加勒比 ----------
    "Antigua and Barbuda": ["首都：圣约翰 Saint John's /seɪnt dʒɒnz/", "缩写：AG"],
    "The Bahamas": ["首都：拿骚 Nassau /ˈnæsɔː/", "缩写：BS"],
    "Barbados": ["首都：布里奇顿 Bridgetown /ˈbrɪdʒtaʊn/", "缩写：BB"],
    "Belize": ["首都：贝尔莫潘 Belmopan /ˈbɛlməpæn/", "缩写：BZ"],
    "Canada": ["首都：渥太华 Ottawa /ˈɒtəwɑː/", "缩写：CA"],
    "Costa Rica": ["首都：圣何塞 San José /sæn hoʊˈzeɪ/", "缩写：CR"],
    "Cuba": ["首都：哈瓦那 Havana /həˈvænə/", "缩写：CU"],
    "Dominica": ["首都：罗索 Roseau /roʊˈzoʊ/", "缩写：DM"],
    "Dominican Republic": ["首都：圣多明各 Santo Domingo /ˌsæntoʊ dəˈmɪŋɡoʊ/", "缩写：DO"],
    "El Salvador": ["首都：圣萨尔瓦多 San Salvador /sæn səlvəˈdɔːr/", "缩写：SV"],
    "Grenada": ["首都：圣乔治 St. George's /seɪnt ˈdʒɔːrdʒɪz/", "缩写：GD"],
    "Guatemala": ["首都：危地马拉城 Guatemala City /ˌɡwɑːtəˈmɑːlə ˈsɪti/", "缩写：GT"],
    "Haiti": ["首都：太子港 Port-au-Prince /ˌpɔːrtoʊ ˈprɪns/", "缩写：HT"],
    "Honduras": ["首都：特古西加尔巴 Tegucigalpa /tɪˌɡuːsiˈɡɑːlpə/", "缩写：HN"],
    "Jamaica": ["首都：金斯顿 Kingston /ˈkɪŋstən/", "缩写：JM"],
    "Mexico": ["首都：墨西哥城 Mexico City /ˈmɛksɪkoʊ ˈsɪti/", "缩写：MX"],
    "Nicaragua": ["首都：马那瓜 Managua /məˈnɑːɡwə/", "缩写：NI"],
    "Panama": ["首都：巴拿马城 Panama City /ˌpænəmə ˈsɪti/", "缩写：PA"],
    "Saint Kitts and Nevis": ["首都：巴斯泰尔 Basseterre /ˈbæsˌtɛr/", "缩写：KN"],
    "Saint Lucia": ["首都：卡斯特里 Castries /ˈkæstriːz/", "缩写：LC"],
    "Saint Vincent and the Grenadines": ["首都：金斯敦 Kingstown /ˈkɪŋstaʊn/", "缩写：VC"],
    "Trinidad and Tobago": ["首都：西班牙港 Port of Spain /pɔːrt əv speɪn/", "缩写：TT"],
    "United States": ["首都：华盛顿 Washington /ˈwɒʃɪŋtən/", "缩写：US"],
    # ---------- 南美洲 ----------
    "Argentina": ["首都：布宜诺斯艾利斯 Buenos Aires /ˌbuːnɛs ˈaɪrɪz/", "缩写：AR"],
    "Bolivia": ["首都：苏克雷 Sucre /ˈsuːkrɛ/（法定；政府驻地拉巴斯）", "缩写：BO"],
    "Brazil": ["首都：巴西利亚 Brasília /brəˈzɪliə/", "缩写：BR"],
    "Chile": ["首都：圣地亚哥 Santiago /ˌsæntiˈɑːɡoʊ/", "缩写：CL"],
    "Colombia": ["首都：波哥大 Bogotá /ˈboʊɡətə/", "缩写：CO"],
    "Ecuador": ["首都：基多 Quito /ˈkiːtoʊ/", "缩写：EC"],
    "Guyana": ["首都：乔治敦 Georgetown /ˈdʒɔːrdʒtaʊn/", "缩写：GY"],
    "Paraguay": ["首都：亚松森 Asunción /eɪˈsʊnsjuːn/", "缩写：PY"],
    "Peru": ["首都：利马 Lima /ˈliːmə/", "缩写：PE"],
    "Suriname": ["首都：帕拉马里博 Paramaribo /ˌpærəməˈriːboʊ/", "缩写：SR"],
    "Uruguay": ["首都：蒙得维的亚 Montevideo /ˌmɒntɪˈviːdeɪoʊ/", "缩写：UY"],
    "Venezuela": ["首都：加拉加斯 Caracas /kəˈrækəs/", "缩写：VE"],
    # ---------- 大洋洲 ----------
    "Australia": ["首都：堪培拉 Canberra /ˈkænbərə/", "缩写：AU"],
    "Fiji": ["首都：苏瓦 Suva /ˈsuːvə/", "缩写：FJ"],
    "Kiribati": ["首都：塔拉瓦 Tarawa /təˈrɑːwə/", "缩写：KI"],
    "Marshall Islands": ["首都：马朱罗 Majuro /məˈdʒuːroʊ/", "缩写：MH"],
    "Micronesia": ["首都：帕利基尔 Palikir /pəˈlɪkɪr/", "缩写：FM"],
    "Nauru": ["首都：亚伦区 Yaren /ˈjærən/（法定；无正式首都）", "缩写：NR"],
    "New Zealand": ["首都：惠灵顿 Wellington /ˈwɛlɪŋtən/", "缩写：NZ"],
    "Palau": ["首都：恩吉鲁穆德 Ngerulmud /ŋəˈruːlmʊd/", "缩写：PW"],
    "Papua New Guinea": ["首都：莫尔兹比港 Port Moresby /pɔːrt ˈmɔːrzbi/", "缩写：PG"],
    "Samoa": ["首都：阿皮亚 Apia /ˈɑːpiə/", "缩写：WS"],
    "Solomon Islands": ["首都：霍尼亚拉 Honiara /ˈhoʊniˌɑːrə/", "缩写：SB"],
    "Tonga": ["首都：努库阿洛法 Nuku'alofa /ˌnuːkuː ɑːˈloʊfə/", "缩写：TO"],
    "Tuvalu": ["首都：富纳富提 Funafuti /ˌfuːnəˈfuːti/", "缩写：TV"],
    "Vanuatu": ["首都：维拉港 Port Vila /pɔːrt ˈviːlə/", "缩写：VU"],
    # ---------- 海外领地 / 非会员地区（键名 = 地图返回名） ----------
    "Aland": ["行政中心：马安哈马 Mariehamn /mɑːriːˈhɑːm/", "缩写：AX"],
    "American Samoa": ["行政中心：帕果帕果 Pago Pago /ˌpɑːɡoʊ ˈpɑːɡoʊ/", "缩写：AS"],
    "Bermuda": ["行政中心：哈密尔顿 Hamilton /ˈhæmɪltən/", "缩写：BM"],
    "Br. Indian Ocean Ter.": ["行政中心：迪戈加西亚 Diego Garcia /ˌdiːɡoʊ ˈɡɑːrʃə/（军事基地，无平民）", "缩写：IO"],
    "Cayman Is.": ["行政中心：乔治敦 George Town /ˈdʒɔːrdʒ taʊn/", "缩写：KY"],
    "Curaçao": ["行政中心：威廉斯塔德 Willemstad /ˈwɪləmstɑːt/", "缩写：CW"],
    "Faeroe Is.": ["行政中心：托尔斯港 Tórshavn /ˈtɔːrsˌhɑːvn/", "缩写：FO"],
    "Falkland Is.": ["行政中心：斯坦利 Stanley /ˈstænli/", "缩写：FK"],
    "Fr. Polynesia": ["行政中心：帕皮提 Papeete /ˌpɑːpeɪˈiːti/", "缩写：PF"],
    "Fr. S. Antarctic Lands": ["行政中心：法属南极港 Port-aux-Français /ˌpɔːrtoʊ frɑːnˈseɪ/（轮换科考人员）", "缩写：TF"],
    "Greenland": ["行政中心：努克 Nuuk /nuːk/", "缩写：GL"],
    "Guam": ["行政中心：阿加尼亚 Hagåtña /həˈɡɑːtnjə/", "缩写：GU"],
    "Heard I. and McDonald Is.": ["行政中心：无常住（澳大利亚管理）", "缩写：HM"],
    "Isle of Man": ["行政中心：道格拉斯 Douglas /ˈdʌɡləs/", "缩写：IM"],
    "Jersey": ["行政中心：圣赫利尔 Saint Helier /seɪnt ˈhɛlɪər/", "缩写：JE"],
    "Montserrat": ["行政中心：布雷兹 Brades /breɪdz/（实际；法理普利茅斯已废弃）", "缩写：MS"],
    "N. Cyprus": ["行政中心：北尼科西亚 North Nicosia /nɔːrθ nɪˈkoʊʃə/", "缩写：—（ISO未分配）"],
    "N. Mariana Is.": ["行政中心：塞班岛 Capitol Hill /ˌkæpɪˈtɒl hɪl/", "缩写：MP"],
    "New Caledonia": ["行政中心：努美阿 Nouméa /nuːˈmeɪə/", "缩写：NC"],
    "Niue": ["行政中心：阿洛菲 Alofi /əˈlɒfi/", "缩写：NU"],
    "Puerto Rico": ["行政中心：圣胡安 San Juan /ˌsɑːn huˈɑːn/", "缩写：PR"],
    "S. Geo. and S. Sandw. Is.": ["行政中心：格里特维肯 Grytviken /ˈɡrɪtvɪkən/（科研站）", "缩写：GS"],
    "Saint Helena": ["行政中心：詹姆斯敦 Jamestown /ˈdʒeɪmztaʊn/", "缩写：SH"],
    "Siachen Glacier": ["行政中心：无（无人区，印巴军事对峙区）", "缩写：—（ISO未分配）"],
    "St. Pierre and Miquelon": ["行政中心：圣皮埃尔 Saint-Pierre /seɪnt ˈpjɛər/", "缩写：PM"],
    "Turks and Caicos Is.": ["行政中心：科克本镇 Cockburn Town /ˈkoʊkbɜːrn taʊn/", "缩写：TC"],
    "U.S. Virgin Is.": ["行政中心：夏洛特阿马利亚 Charlotte Amalie /ʃɑːrˈlɒt əˈmɑːli/", "缩写：VI"],
    "W. Sahara": ["行政中心：阿尤恩 El Aaiún /el aɪˈuːn/（摩洛哥实控）", "缩写：EH"],
}

# 把首都/缩写字段并入国家信息（就地 extend；别名共享同一对象，自动同步）
for _k, _v in capital_abbr.items():
    if _k in country_info:
        country_info[_k].extend(_v)

# 国际奥委会（IOC）三国字母代码：规范名/地图名 -> 代码
# 依据 IOC 现行 206 个 NOC 成员代码体系（经数据集与奥委会官方序列名单核对；
# 南苏丹 SSD 为官方礼宾序列确认补录）。未单列的地区标"非国际奥委会成员"。
ioc_map = {
    "Afghanistan": "AFG", "Albania": "ALB", "Algeria": "ALG", "Andorra": "AND",
    "Angola": "ANG", "Antigua and Barbuda": "ANT", "Argentina": "ARG", "Armenia": "ARM",
    "Australia": "AUS", "Austria": "AUT", "Azerbaijan": "AZE",
    "The Bahamas": "BAH", "Bahrain": "BRN", "Bangladesh": "BAN", "Barbados": "BAR",
    "Belarus": "BLR", "Belgium": "BEL", "Belize": "BIZ", "Benin": "BEN",
    "Bhutan": "BHU", "Bolivia": "BOL", "Bosnia and Herzegovina": "BIH",
    "Botswana": "BOT", "Brazil": "BRA", "Brunei": "BRU", "Bulgaria": "BUL",
    "Burkina Faso": "BUR", "Burundi": "BDI",
    "Cabo Verde": "CPV", "Cambodia": "CAM", "Cameroon": "CMR", "Canada": "CAN",
    "Central African Republic": "CAF", "Chad": "CHA", "Chile": "CHI", "China": "CHN",
    "Colombia": "COL", "Comoros": "COM", "Congo": "CGO",
    "Democratic Republic of the Congo": "COD", "Costa Rica": "CRC", "Croatia": "CRO",
    "Cuba": "CUB", "Cyprus": "CYP", "Czech Republic": "CZE", "Côte d'Ivoire": "CIV",
    "Denmark": "DEN", "Djibouti": "DJI", "Dominica": "DMA", "Dominican Republic": "DOM",
    "East Timor": "TLS", "Ecuador": "ECU", "Egypt": "EGY",
    "El Salvador": "ESA", "Equatorial Guinea": "GEQ", "Eritrea": "ERI", "Eswatini": "SWZ",
    "Estonia": "EST", "Ethiopia": "ETH",
    "Fiji": "FIJ", "Finland": "FIN", "France": "FRA", "Gabon": "GAB", "Gambia": "GAM",
    "Georgia": "GEO", "Germany": "GER", "Ghana": "GHA", "Greece": "GRE", "Grenada": "GRN",
    "Guatemala": "GUA", "Guinea": "GUI", "Guinea-Bissau": "GBS", "Guyana": "GUY",
    "Haiti": "HAI", "Honduras": "HON", "Hungary": "HUN", "Iceland": "ISL", "India": "IND",
    "Indonesia": "INA", "Iran": "IRI", "Iraq": "IRQ", "Ireland": "IRL", "Israel": "ISR",
    "Italy": "ITA", "Ivory Coast": "CIV",
    "Jamaica": "JAM", "Japan": "JPN", "Jordan": "JOR", "Kazakhstan": "KAZ",
    "Kenya": "KEN", "Kiribati": "KIR", "Kosovo": "KOS", "Kuwait": "KUW",
    "Kyrgyzstan": "KGZ", "Laos": "LAO", "Latvia": "LAT", "Lebanon": "LBN",
    "Lesotho": "LES", "Liberia": "LBR", "Libya": "LBA", "Liechtenstein": "LIE",
    "Lithuania": "LTU", "Luxembourg": "LUX",
    "Madagascar": "MAD", "Malawi": "MAW", "Malaysia": "MAS", "Maldives": "MDV", "Mali": "MLI",
    "Malta": "MLT", "Marshall Islands": "MHL", "Mauritania": "MTN", "Mauritius": "MRI",
    "Mexico": "MEX", "Micronesia": "FSM", "Moldova": "MDA", "Monaco": "MON",
    "Mongolia": "MGL", "Montenegro": "MNE", "Morocco": "MAR", "Mozambique": "MOZ",
    "Myanmar": "MYA", "Namibia": "NAM", "Nauru": "NRU", "Nepal": "NEP",
    "Netherlands": "NED", "New Zealand": "NZL", "Nicaragua": "NCA", "Niger": "NIG",
    "Nigeria": "NGR", "North Korea": "PRK", "North Macedonia": "MKD", "Norway": "NOR",
    "Oman": "OMA", "Pakistan": "PAK", "Palau": "PLW", "Palestine": "PLE",
    "Panama": "PAN", "Papua New Guinea": "PNG", "Paraguay": "PAR", "Peru": "PER",
    "Philippines": "PHI", "Poland": "POL", "Portugal": "POR", "Qatar": "QAT",
    "Romania": "ROU", "Russia": "RUS", "Rwanda": "RWA",
    "Saint Kitts and Nevis": "SKN", "Saint Lucia": "LCA",
    "Saint Vincent and the Grenadines": "VIN", "Samoa": "SAM", "San Marino": "SMR",
    "São Tomé and Príncipe": "STP", "Saudi Arabia": "KSA", "Senegal": "SEN",
    "Serbia": "SRB", "Seychelles": "SEY", "Sierra Leone": "SLE", "Singapore": "SGP",
    "Slovakia": "SVK", "Slovenia": "SLO", "Solomon Islands": "SOL", "Somalia": "SOM",
    "South Africa": "RSA", "South Korea": "KOR", "South Sudan": "SSD", "Spain": "ESP",
    "Sri Lanka": "SRI", "Sudan": "SUD", "Suriname": "SUR", "Sweden": "SWE",
    "Switzerland": "SUI", "Syria": "SYR", "Tajikistan": "TJK", "Tanzania": "TAN",
    "Thailand": "THA", "Togo": "TOG", "Tonga": "TGA",
    "Trinidad and Tobago": "TTO", "Tunisia": "TUN", "Turkey": "TUR", "Turkmenistan": "TKM",
    "Tuvalu": "TUV", "UAE": "UAE", "Uganda": "UGA", "Ukraine": "UKR",
    "United Kingdom": "GBR", "United States": "USA", "Uruguay": "URU", "Uzbekistan": "UZB",
    "Vanuatu": "VAN", "Venezuela": "VEN", "Vietnam": "VIE", "Yemen": "YEM",
    "Zambia": "ZAM", "Zimbabwe": "ZIM",
    # 有奥委会代码的非主权地区
    "American Samoa": "ASA", "Bermuda": "BER", "Cayman Is.": "CAY", "Guam": "GUM",
    "Puerto Rico": "PUR", "U.S. Virgin Is.": "ISV",
}

# 并入缩写行：ISO 两字母码 + 奥委会三字母码合并显示，如 "缩写：CN, CHN"
# 无奥委会代码的地区如实括注原因；ISO 亦未分配时并列说明。
_ioc_note = {
    "梵蒂冈": "—（未组建奥委会）",
    "北塞浦路斯": "—（未获国际奥委会承认）",
    "锡亚琴冰川": "—（无人区）",
}
_seen_ids = set()
for _lst in country_info.values():
    if id(_lst) in _seen_ids:
        continue  # 别名与规范名共享同一列表，只处理一次
    _seen_ids.add(id(_lst))
    _ioc = _ioc_note.get(_lst[1], "")
    if not _ioc:
        _k8 = [k for k, v in country_info.items() if v is _lst and k in ioc_map]
        _ioc = ioc_map[_k8[0]] if _k8 else "—（非国际奥委会成员）"
    _raw = _lst[6].split("：", 1)[1].strip()   # 全角冒号后的内容，如 "AF" 或 "—（ISO未分配）"
    _iso = _raw.split("（")[0].strip()         # alpha-2 码或 "—"
    if not _ioc.startswith("—"):
        _lst[6] = f"缩写：{_iso}, {_ioc}"
    else:
        _note = _ioc.strip("—（） ")
        if _iso == "—":
            _lst[6] = f"缩写：—（ISO未分配；{_note}）"
        else:
            _lst[6] = f"缩写：{_iso}（{_note}）"

# 官方语言（规范名 -> 中文语言名，顿号分隔；来源 mledoze/countries 语言字段并经修正）
# 数据口径：de facto/法定官方语言；英联邦部分国家英语为实际行政语言。
country_lang = {
    "Afghanistan": "达里语、普什图语、土库曼语",
    "Armenia": "亚美尼亚语",
    "Azerbaijan": "阿塞拜疆语、俄语",
    "Bahrain": "阿拉伯语",
    "Bangladesh": "孟加拉语",
    "Bhutan": "宗卡语",
    "Brunei": "马来语",
    "Cambodia": "高棉语",
    "China": "中文",
    "Cyprus": "希腊语、土耳其语",
    "East Timor": "葡萄牙语、德顿语",
    "Georgia": "格鲁吉亚语",
    "India": "印地语、英语",
    "Indonesia": "印度尼西亚语",
    "Iran": "波斯语",
    "Iraq": "阿拉伯语、亚拉姆语、索拉尼库尔德语",
    "Israel": "阿拉伯语、希伯来语",
    "Japan": "日语",
    "Jordan": "阿拉伯语",
    "Kazakhstan": "哈萨克语、俄语",
    "Kuwait": "阿拉伯语",
    "Kyrgyzstan": "吉尔吉斯语、俄语",
    "Laos": "老挝语",
    "Lebanon": "阿拉伯语、法语",
    "Malaysia": "英语、马来语",
    "Maldives": "迪维希语",
    "Mongolia": "蒙古语",
    "Myanmar": "缅甸语",
    "Nepal": "尼泊尔语",
    "North Korea": "韩语",
    "Oman": "阿拉伯语",
    "Pakistan": "英语、乌尔都语",
    "Philippines": "英语、菲律宾语",
    "Qatar": "阿拉伯语",
    "Saudi Arabia": "阿拉伯语",
    "Singapore": "中文、英语、马来语、泰米尔语",
    "South Korea": "韩语",
    "Sri Lanka": "僧伽罗语、泰米尔语",
    "Syria": "阿拉伯语",
    "Tajikistan": "俄语、塔吉克语",
    "Thailand": "泰语",
    "Turkey": "土耳其语",
    "Turkmenistan": "俄语、土库曼语",
    "UAE": "阿拉伯语",
    "Uzbekistan": "俄语、乌兹别克语",
    "Vietnam": "越南语",
    "Yemen": "阿拉伯语",
    "Palestine": "阿拉伯语",
    "Algeria": "阿拉伯语",
    "Angola": "葡萄牙语",
    "Benin": "法语",
    "Botswana": "英语、茨瓦纳语",
    "Burkina Faso": "法语",
    "Burundi": "法语、基隆迪语",
    "Cabo Verde": "葡萄牙语",
    "Cameroon": "英语、法语",
    "Central African Republic": "法语、桑戈语",
    "Chad": "阿拉伯语、法语",
    "Comoros": "阿拉伯语、科摩罗语、法语",
    "Congo": "法语、基孔戈语、林加拉语",
    "Democratic Republic of the Congo": "法语、基孔戈语、林加拉语、斯瓦希里语、奇卢巴语",
    "Côte d'Ivoire": "法语",
    "Djibouti": "阿拉伯语、法语",
    "Egypt": "阿拉伯语",
    "Equatorial Guinea": "法语、葡萄牙语、西班牙语",
    "Eritrea": "阿拉伯语、英语、提格里尼亚语",
    "Eswatini": "英语、斯瓦蒂语",
    "Ethiopia": "阿姆哈拉语",
    "Gabon": "法语",
    "Gambia": "英语",
    "Ghana": "英语",
    "Guinea": "法语",
    "Guinea-Bissau": "葡萄牙语、上几内亚克里奥尔语",
    "Kenya": "英语、斯瓦希里语",
    "Lesotho": "英语、索托语",
    "Liberia": "英语",
    "Libya": "阿拉伯语",
    "Madagascar": "法语、马达加斯加语",
    "Malawi": "奇切瓦语、英语",
    "Mali": "法语",
    "Mauritania": "阿拉伯语",
    "Mauritius": "英语、法语、毛里求斯克里奥尔语",
    "Morocco": "阿拉伯语、柏柏尔语",
    "Mozambique": "葡萄牙语",
    "Namibia": "南非荷兰语、英语、德语、赫雷罗语、科伊科伊语、宽加利语、洛齐语、恩东加语、茨瓦纳语",
    "Niger": "法语",
    "Nigeria": "英语",
    "Rwanda": "英语、法语、卢旺达语",
    "São Tomé and Príncipe": "葡萄牙语",
    "Senegal": "法语",
    "Seychelles": "英语、法语、塞舌尔克里奥尔语",
    "Sierra Leone": "英语",
    "Somalia": "阿拉伯语、索马里语",
    "South Africa": "南非荷兰语、英语、北索托语、南恩德贝莱语、南索托语、斯瓦蒂语、聪加语、茨瓦纳语、文达语、科萨语、祖鲁语",
    "South Sudan": "英语",
    "Sudan": "阿拉伯语、英语",
    "Tanzania": "英语、斯瓦希里语",
    "Togo": "法语",
    "Tunisia": "阿拉伯语",
    "Uganda": "英语、斯瓦希里语",
    "Zambia": "英语",
    "Zimbabwe": "奇切瓦语、齐巴韦语、英语、卡兰加语、科伊桑语、恩道语、北恩德贝莱语、绍纳语、索托语、通加语、聪加语、茨瓦纳语、文达语、科萨语、津巴布韦手语",
    "Albania": "阿尔巴尼亚语",
    "Andorra": "加泰罗尼亚语",
    "Austria": "德语",
    "Belarus": "白俄罗斯语、俄语",
    "Belgium": "荷兰语、法语、德语",
    "Bosnia and Herzegovina": "波斯尼亚语、克罗地亚语、塞尔维亚语",
    "Bulgaria": "保加利亚语",
    "Croatia": "克罗地亚语",
    "Czech Republic": "捷克语",
    "Denmark": "丹麦语",
    "Estonia": "爱沙尼亚语",
    "Finland": "芬兰语、瑞典语",
    "France": "法语",
    "Germany": "德语",
    "Greece": "希腊语",
    "Hungary": "匈牙利语",
    "Iceland": "冰岛语",
    "Ireland": "英语、爱尔兰语",
    "Italy": "意大利语",
    "Latvia": "拉脱维亚语",
    "Liechtenstein": "德语",
    "Lithuania": "立陶宛语",
    "Luxembourg": "法语、德语、卢森堡语",
    "Malta": "英语、马耳他语",
    "Moldova": "摩尔多瓦语",
    "Monaco": "法语",
    "Montenegro": "黑山语",
    "Netherlands": "荷兰语",
    "North Macedonia": "马其顿语",
    "Norway": "书面挪威语、新挪威语、萨米语",
    "Poland": "波兰语",
    "Portugal": "葡萄牙语",
    "Romania": "罗马尼亚语",
    "Russia": "俄语",
    "San Marino": "意大利语",
    "Serbia": "塞尔维亚语",
    "Slovakia": "斯洛伐克语",
    "Slovenia": "斯洛文尼亚语",
    "Spain": "西班牙语",
    "Sweden": "瑞典语",
    "Switzerland": "德语、法语、意大利语、罗曼什语",
    "Ukraine": "乌克兰语",
    "United Kingdom": "英语",
    "Vatican": "意大利语、拉丁语",
    "Antigua and Barbuda": "英语",
    "The Bahamas": "英语",
    "Barbados": "英语",
    "Belize": "伯利兹克里奥尔语、英语、西班牙语",
    "Canada": "英语、法语",
    "Costa Rica": "西班牙语",
    "Cuba": "西班牙语",
    "Dominica": "英语",
    "Dominican Republic": "西班牙语",
    "El Salvador": "西班牙语",
    "Grenada": "英语",
    "Guatemala": "西班牙语",
    "Haiti": "法语、海地克里奥尔语",
    "Honduras": "西班牙语",
    "Jamaica": "英语、牙买加克里奥尔语",
    "Mexico": "西班牙语",
    "Nicaragua": "西班牙语",
    "Panama": "西班牙语",
    "Saint Kitts and Nevis": "英语",
    "Saint Lucia": "英语",
    "Saint Vincent and the Grenadines": "英语",
    "Trinidad and Tobago": "英语",
    "United States": "英语",
    "Argentina": "瓜拉尼语、西班牙语",
    "Bolivia": "艾马拉语、瓜拉尼语、克丘亚语、西班牙语",
    "Brazil": "葡萄牙语",
    "Chile": "西班牙语",
    "Colombia": "西班牙语",
    "Ecuador": "西班牙语",
    "Guyana": "英语",
    "Paraguay": "瓜拉尼语、西班牙语",
    "Peru": "艾马拉语、克丘亚语、西班牙语",
    "Suriname": "荷兰语",
    "Uruguay": "西班牙语",
    "Venezuela": "西班牙语",
    "Australia": "英语",
    "Fiji": "英语、斐济印地语、斐济语",
    "Kiribati": "英语、基里巴斯语",
    "Marshall Islands": "英语、马绍尔语",
    "Micronesia": "英语",
    "Nauru": "英语、瑙鲁语",
    "New Zealand": "英语、毛利语、新西兰手语",
    "Palau": "英语、帕劳语",
    "Papua New Guinea": "英语、希里莫图语、托克皮辛语",
    "Samoa": "英语、萨摩亚语",
    "Solomon Islands": "英语",
    "Tonga": "英语、汤加语",
    "Tuvalu": "英语、图瓦卢语",
    "Vanuatu": "比斯拉马语、英语、法语",
    "Aland": "瑞典语",
    "American Samoa": "英语、萨摩亚语",
    "Bermuda": "英语",
    "Br. Indian Ocean Ter.": "英语",
    "Cayman Is.": "英语",
    "Curaçao": "荷兰语、英语、帕普利亚门托语",
    "Faeroe Is.": "丹麦语、法罗语",
    "Falkland Is.": "英语",
    "Fr. Polynesia": "法语",
    "Fr. S. Antarctic Lands": "法语",
    "Greenland": "格陵兰语",
    "Guam": "查莫罗语、英语、西班牙语",
    "Heard I. and McDonald Is.": "英语",
    "Isle of Man": "英语、马恩语",
    "Jersey": "英语、法语、泽西语",
    "Montserrat": "英语",
    "N. Cyprus": "土耳其语",
    "N. Mariana Is.": "加罗林语、查莫罗语、英语",
    "New Caledonia": "法语",
    "Niue": "英语、纽埃语",
    "Puerto Rico": "英语、西班牙语",
    "S. Geo. and S. Sandw. Is.": "英语",
    "Saint Helena": "英语",
    "Siachen Glacier": "—（无人区）",
    "St. Pierre and Miquelon": "法语",
    "Turks and Caicos Is.": "英语",
    "U.S. Virgin Is.": "英语",
    "W. Sahara": "柏柏尔语、哈桑尼亚语、西班牙语",
}

# 追加官方语言到国家信息（别名共享同一对象，只处理一次）
_seen_ids2 = set()
for _lst in country_info.values():
    if id(_lst) in _seen_ids2:
        continue
    _seen_ids2.add(id(_lst))
    _k9 = [k for k, v in country_info.items() if v is _lst and k in country_lang]
    _lang = country_lang.get(_k9[0]) if _k9 else None
    _lst.append("官方语言：" + (_lang if _lang else "—"))

# 1. 准备分组数据 (国家, 数值)
# 这里用各大洲作为分组示例，你可以替换成任何你想要的分组逻辑

# 第一组：亚洲部分国家 (value: 30)
group_1 = [
    ("China", 90), ("Japan", 60), ("South Korea", 30),
    ("India", 10), ("Thailand", 70), ("Vietnam", 20)
]

# 第二组：欧洲部分国家 (value: 50)
group_2 = [
    ("Russia", 0), ("Germany", 20), ("France", 50),
    ("United Kingdom", 90), ("Italy", 40), ("Spain", 80)
]

# 第三组：美洲部分国家 (value: 70)
group_3 = [
    ("United States", 10), ("Canada", 50), ("Brazil", 70),
    ("Mexico", 9), ("Argentina", 30)
]

# 第四组：其他大洲国家 (value: 90)
group_4 = [
    ("Australia", 10), ("Egypt", 40), ("South Africa", 70),
    ("Nigeria", 90), ("Saudi Arabia", 20)
]

# 合并所有数据
data = group_1 + group_2 + group_3 + group_4

# 2. 创建全屏地图
c = (
    Map(init_opts=opts.InitOpts(width="100%", height="100vh"))
    .add(
        "",
        data,
        "world",  # 核心改动：地图类型从 "china" 变为 "world"
        label_opts=opts.LabelOpts(is_show=False), # 隐藏国家名
    )
    .set_global_opts(
        visualmap_opts=opts.VisualMapOpts(is_show=False),
        tooltip_opts=opts.TooltipOpts(
            is_show=True,
            trigger="item",
            formatter=JsCode(
                "function(p){"
                "var info=countryInfo[p.name];"
                "if(!info){return p.name;}"
                "return '<div style=\"line-height:1.8\">'"
                "+'<b>'+info[1]+'</b>（'+p.name+'  '+info[0]+'）<br>'"
                "+'大洲：'+info[2]+'<br>'"
                "+'面积：'+info[3]+'<br>'"
                "+'人口：'+info[4]+'<br>'"
                "+info[5]+'<br>'"
                "+info[6]+'<br>'"
                "+info[7]+'</div>';"
                "}"
            ),
        ), # 悬停显示国家信息卡片
    )
)

# 3. 注入国家信息字典（json.dumps 保证含撇号等国家名不破坏 JS）
c.add_js_funcs("var countryInfo = " + json.dumps(country_info, ensure_ascii=False) + ";")

# 4. 注入 CSS，去掉页面默认边距，实现真正全屏
c.add_js_funcs("""
    document.body.style.margin = '0';
    document.body.style.padding = '0';
    document.body.style.overflow = 'hidden';
""")

# 5. 生成文件
c.render("worldBlank.html")
print("世界地图已生成，请查看 worldBlank.html")
